name: 'DISCORD PUSH'
on:
  push:
    branches:
      - main
    
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: " "
          message: "**Автор:** ${{ github.event.pusher.username }} \n**Ветка:** ${{ github.event.ref }} \n**Описание:** ${{ github.event.compare }} \n${{ github.event.head_commit.url }}"
          include_image: true
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          username: "Shiptest: Changelog"
