name: 'Discord Notification'

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # Формируем список коммитов и их количество только для push
      - name: Get commit count
        if: github.event_name == 'push'
        id: count
        run: |
          echo "COMMITS_COUNT=$(jq '.commits | length' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Format commit list
        if: github.event_name == 'push'
        id: commits
        run: |
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          jq -r '.commits[] | "[`" + (.id[0:7]) + "`](" + .url + ") " + .message + " - " + .author.name' $GITHUB_EVENT_PATH >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Отправка уведомления в Discord для push
      - name: Send Discord notification (push)
        if: github.event_name == 'push'
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: "[${{ github.repository }}:${{ github.ref_name }}] ${{ env.COMMITS_COUNT }} new commits"
          message: |
            ${{ env.COMMITS }}
          username: ${{ github.event.pusher.name }}

      # Отправка уведомления в Discord для закрытого PR (без коммитов)
      - name: Send Discord notification (PR closed)
        if: github.event_name == 'pull_request'
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: ${{ github.event.pull_request.title }}
          message: "**Ветка:** ${{ github.event.pull_request.base.ref }} **\n Описание:** ${{ github.event.pull_request.body }} \n**Creator:** ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}"
          include_image: true
          avatar_url: ${{ github.event.pull_request.user.avatar_url }}
          username: ${{ github.event.pull_request.user.login }}
