name: Discord Notify Commits

on:
  push:
    branches:
      - main # или нужная ветка

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Format commit list
        id: commits
        run: |
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          jq -r '.commits[] | "[`" + (.id[0:7]) + "`](" + .url + ") " + .message + " - " + .author.name' $GITHUB_EVENT_PATH >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Discord notification
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: "1[${{ github.repository }}:${{ github.ref_name }}] ${{ github.event.commits | length }} new commits"
          message: |
            ${{ env.COMMITS }}
          username: ${{ github.event.pusher.name }}
